# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - group: add-iterations-to-azure-devops-project

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - script: az devops -h
#   displayName: 'Run a one-line script'

- task: PowerShell@2
  displayName: 'Run the ps script'
  inputs:
    filePath: '$(build.sourcesdirectory)/createIterations.ps1'
    arguments: -PAT "$(PAT)"